version: '3.8'

services:
  img-manip:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    environment: #TODO: Read this from .env file
      - PYTHONUNBUFFERED=1  # Ensure logs are flushed to the console
      - DB_HOST=db
      - DB_USER=user
      - DB_PASSWORD=password
      - DB_NAME=image_db
    depends_on:
      - db

  db:
    image: mysql:latest
    restart: always
    environment: #TODO: Read this from .env file
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=image_db
      - MYSQL_USER=user
      - MYSQL_PASSWORD=password
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql

  adminer:
    image: adminer
    restart: always
    ports:
      - "8080:8080"
    depends_on:
      - db

volumes:
  mysql-data: